# (C) 2020-2021 Evolveum

require 'evolveum/common'
require 'evolveum/jekyll-nav-plugin'
require 'evolveum/jekyll-git-plugin'
require 'evolveum/jekyll-sitemap-plugin'
require 'evolveum/jekyll-redirect-plugin'
require 'evolveum/jekyll-samples-plugin'
require 'evolveum/jekyll-versionlink-plugin'
require 'evolveum/jekyll-versioning-plugin'
require 'evolveum/jekyll-release-plugin'
require 'evolveum/jekyll-feature-plugin'
require 'evolveum/jekyll-filters-plugin'
require 'evolveum/jekyll-book-plugin'
require 'evolveum/jekyll-divblock-plugin'
require 'evolveum/asciidoctor-plugin'