permalink: pretty
twitter_username: evolveum
github_username:  Evolveum

plugins:
  - evolveum-jekyll-plugin
  - jekyll-asciidoc

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    source-highlighter: rouge

docs:
  docsPath: ../
  docsDirName: docs
  midpointVersionsPath: ../
  midpointVersionsPrefix: mp-
  midpointSamplesPath: ../
  midpointSamplesDirName: mp-samples


highlighter: rouge
