permalink: pretty
twitter_username: evolveum
github_username:  Evolveum

plugins:
  - evolveum-jekyll-plugin
  - jekyll-asciidoc
  - coderay

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    source-highlighter: coderay
